### ISSUE TITLE
Dash in parameter names

### ISSUE THREAD

**Issue by stewartmckee** [SmartBear/ruby-handlebars#15]
I'm having an issue with dash in a param for example:

    handlebars = Huddle::Handlebars.new("hi {{foo-bar}}")

results in 

    Parslet::ParseFailed (Extra input after last repetition at line 1 char 4.)

I have the same templates causing the error working fine on handlebars.js.  I'm forking just now to take a look, but anyone seen this before with a resolution?

**Comment by vincent-psarga** [comment]
That was release in 0.2 (and I forgot to close the issue :/ )
